const crypto = require("crypto");
const readline = require("readline");

class OperatorConsoleProvider {
  constructor() {
    this.promptQueue = Promise.resolve();
  }

  async health() {
    return {
      provider: "operator_console",
      ready: Boolean(process.stdin.isTTY && process.stdout.isTTY),
      message:
        process.stdin.isTTY && process.stdout.isTTY
          ? "Operator console bridge is ready."
          : "Operator console bridge needs an interactive terminal.",
    };
  }

  async enroll(payload = {}) {
    const subjectLabel = String(
      payload.label || `${payload.subjectType || "person"} ${payload.subjectId || ""}`
    ).trim();
    const templateRef = await this.prompt(
      [
        "",
        "[Fingerprint Bridge] Enrollment requested",
        `Subject: ${subjectLabel || "Unknown subject"}`,
        "Type a template reference from the scanner workflow, or press Enter to generate one:",
      ].join("\n")
    );

    const normalizedTemplateRef = templateRef || `fp_${crypto.randomUUID()}`;

    return {
      provider: "operator_console",
      templateRef: normalizedTemplateRef,
      deviceName: "Operator Console",
      qualityScore: null,
      message: templateRef
        ? "Template reference captured from operator console."
        : "Template reference generated by operator console bridge.",
    };
  }

  async identify(payload = {}) {
    const templateRef = await this.prompt(
      [
        "",
        "[Fingerprint Bridge] Identification requested",
        `Scope: ${String(payload.scope || "general").trim() || "general"}`,
        `Event: ${String(payload.eventId || "").trim() || "n/a"}`,
        "Type the matching template reference and press Enter:",
      ].join("\n")
    );

    if (!templateRef) {
      throw new Error("A fingerprint template reference is required to identify the scan.");
    }

    return {
      provider: "operator_console",
      templateRef,
      deviceName: "Operator Console",
      qualityScore: null,
      message: "Fingerprint match reference captured from operator console.",
    };
  }

  async prompt(message) {
    this.assertInteractiveTerminal();

    const runPrompt = async () =>
      new Promise((resolve) => {
        const reader = readline.createInterface({
          input: process.stdin,
          output: process.stdout,
        });

        reader.question(`${message}\n> `, (answer) => {
          reader.close();
          resolve(String(answer || "").trim());
        });
      });

    const nextPrompt = this.promptQueue.then(runPrompt, runPrompt);
    this.promptQueue = nextPrompt.then(
      () => undefined,
      () => undefined
    );
    return nextPrompt;
  }

  assertInteractiveTerminal() {
    if (!process.stdin.isTTY || !process.stdout.isTTY) {
      throw new Error("Fingerprint bridge is running without an interactive terminal.");
    }
  }
}

module.exports = OperatorConsoleProvider;
