const ROLES = {
  SYSTEM_ADMINISTRATOR: "System Administrator",
  CHURCH_ADMINISTRATOR: "Church Administrator",
  ELDERS: "Elders",
  DEACONS: "Deacons",
  MINISTRY_LEADERS: "Ministry Leaders",
  EVANGELISM_TEAM: "Evangelism Team",
  DATA_ENTRY_CLERKS: "Data Entry Clerks",
  MEMBER_PORTAL: "Members Portal",
};

const PERMISSIONS = {
  MANAGE_SYSTEM: "manage_system",
  MANAGE_LOOKUPS: "manage_lookups",
  MANAGE_USERS: "manage_users",
  VIEW_AUDIT_LOGS: "view_audit_logs",
  MANAGE_VISITORS: "manage_visitors",
  VIEW_VISITORS: "view_visitors",
  ASSIGN_VISITOR_FOLLOWUP: "assign_visitor_followup",
  CONVERT_VISITOR: "convert_visitor",
  MANAGE_EVANGELISM: "manage_evangelism",
  VIEW_EVANGELISM: "view_evangelism",
  CONVERT_PROSPECT: "convert_prospect",
  VIEW_PENDING_ACTIONS: "view_pending_actions",
};

const ROLE_PERMISSION_MAP = {
  [ROLES.SYSTEM_ADMINISTRATOR]: [
    PERMISSIONS.MANAGE_SYSTEM,
    PERMISSIONS.MANAGE_LOOKUPS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_VISITORS,
    PERMISSIONS.VIEW_VISITORS,
    PERMISSIONS.ASSIGN_VISITOR_FOLLOWUP,
    PERMISSIONS.CONVERT_VISITOR,
    PERMISSIONS.MANAGE_EVANGELISM,
    PERMISSIONS.VIEW_EVANGELISM,
    PERMISSIONS.CONVERT_PROSPECT,
    PERMISSIONS.VIEW_PENDING_ACTIONS,
  ],
  [ROLES.CHURCH_ADMINISTRATOR]: [
    PERMISSIONS.MANAGE_LOOKUPS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_VISITORS,
    PERMISSIONS.VIEW_VISITORS,
    PERMISSIONS.ASSIGN_VISITOR_FOLLOWUP,
    PERMISSIONS.CONVERT_VISITOR,
    PERMISSIONS.MANAGE_EVANGELISM,
    PERMISSIONS.VIEW_EVANGELISM,
    PERMISSIONS.CONVERT_PROSPECT,
    PERMISSIONS.VIEW_PENDING_ACTIONS,
  ],
  [ROLES.ELDERS]: [
    PERMISSIONS.VIEW_VISITORS,
    PERMISSIONS.VIEW_EVANGELISM,
    PERMISSIONS.VIEW_PENDING_ACTIONS,
  ],
  [ROLES.DEACONS]: [
    PERMISSIONS.VIEW_VISITORS,
    PERMISSIONS.VIEW_EVANGELISM,
    PERMISSIONS.VIEW_PENDING_ACTIONS,
  ],
  [ROLES.MINISTRY_LEADERS]: [
    PERMISSIONS.VIEW_VISITORS,
    PERMISSIONS.VIEW_EVANGELISM,
    PERMISSIONS.VIEW_PENDING_ACTIONS,
  ],
  [ROLES.EVANGELISM_TEAM]: [
    PERMISSIONS.MANAGE_VISITORS,
    PERMISSIONS.VIEW_VISITORS,
    PERMISSIONS.ASSIGN_VISITOR_FOLLOWUP,
    PERMISSIONS.CONVERT_VISITOR,
    PERMISSIONS.MANAGE_EVANGELISM,
    PERMISSIONS.VIEW_EVANGELISM,
    PERMISSIONS.CONVERT_PROSPECT,
    PERMISSIONS.VIEW_PENDING_ACTIONS,
  ],
  [ROLES.DATA_ENTRY_CLERKS]: [
    PERMISSIONS.MANAGE_VISITORS,
    PERMISSIONS.VIEW_VISITORS,
    PERMISSIONS.VIEW_EVANGELISM,
  ],
  [ROLES.MEMBER_PORTAL]: [],
};

module.exports = {
  PERMISSIONS,
  ROLES,
  ROLE_PERMISSION_MAP,
};
